services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: python-devsecops-jenkins_app:latest
    container_name: flask-devsecops-app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - PORT=5000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s